services:
  darkwg:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: darkwg
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file:
      - /etc/darkwg/api.env
    volumes:
      - /etc/darkwg:/etc/darkwg
      - darkwg-data:/opt/darkwg/data
      - __AWG_BIN_PATH__:/usr/local/bin/darkwg:ro
      - __AWG_QUICK_BIN_PATH__:/usr/local/bin/darkwg-quick:ro

  darkwg-nginx:
    image: nginx:1.28
    container_name: darkwg-nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx/darkwg-api.conf:/etc/nginx/conf.d/darkwg-api.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - darkwg
    profiles:
      - external

volumes:
  darkwg-data:
